### ISSUE TITLE
Move database into seperate container

### ISSUE THREAD

**Issue by CptPie** [strichliste/strichliste-docker#2]
The current setup with the included database works but is a bit hacky

- [x] explore how to move the database into a container
- [x] explore if it is possible to maintain the current tables
- [x] update docker-compose file to use a db image
- [x] test if everything works as expected

**Comment by schinken** [comment]
You can also use a mysql or postgres for strichliste - no need to use sqlite, btw :)
But I actually don't know how to backup your database then...

**Comment by CptPie** [comment]
done as by version 1.6.2
