### ISSUE TITLE
Use any other database than sqlite

### ISSUE THREAD

**Issue by schinken** [strichliste/strichliste-docker#4]
sqlite does not support needed transactional features. I've updated the server package and the documentation on the website already

**Comment by CptPie** [comment]
I am currently working on moving the database to postgreSQL.
@schinken does the backend create the database and the corresponding tables or is it necessary to already have a database / all tables created?

**Comment by schinken** [comment]
If you have created the database, you just have to run `php bin/console doctrine:schema:create`

**Comment by schinken** [comment]
I've got an idea how I maybe can get this working again with sqlite

**Comment by CptPie** [comment]
I think it should be rather easy to use some other database (postgres/mysql), so no need to cling on sqlite. On the other side i have trouble to get the communication between the database container and the strichliste container working.

**Comment by CptPie** [comment]
Done as by Release 1.6.2
