### ISSUE TITLE
Update strichliste Repo

### ISSUE THREAD

**Issue by schinken** [strichliste/strichliste-docker#6]
See https://www.strichliste.org/news/builds/

**Comment by CptPie** [comment]
done, see https://github.com/strichliste/strichliste-docker/releases/tag/v.1.4.0

**Comment by schinken** [comment]
I would totally recommend that you use the release from https://github.com/strichliste/strichliste 
This already contains backend and frontend bundled in a compatible way. So you don't have to track which backend and frontend version work perfectly together

Can you change this?

**Comment by CptPie** [comment]
Sure, i will look into it tomorrow :)
